age: 18
aaa: A
context: "aa: ${aaa}, age: ${age}"
boy:
  age: 25
  height: 185
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    url: jdbc:mysql://localhost:3306/zhangbh?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    connectionProperties: druid.stat.mergeSql=true
  http:
    encoding:
      charset: utf-8
      enabled: true
mybatis:
  type-aliases-package: com.glodon.springboothello.domain
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql